# Generated by Django 3.2.9 on 2021-12-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='No Name', max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
