# Generated by Django 3.2.9 on 2021-12-05 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_products_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
