# Generated by Django 3.2.9 on 2021-12-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_products_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AddField(
            model_name='product',
            name='shortcode',
            field=models.CharField(blank=True, default='abc123', max_length=10, null=True),
        ),
    ]
