# Generated by Django 3.2.9 on 2021-12-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_shortcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shortcode',
        ),
        migrations.AddField(
            model_name='product',
            name='sayi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
